### ISSUE TITLE
Process crashes in minimum L1/2/3 format

### ISSUE THREAD

**Issue by gvzdus** [mr-manuel/venus-os_dbus-mqtt-grid#3]
When simply sending the format {power...,"L1":{"power":x}, ...} the process crashes with this output:

```bash
2023-05-22 18:12:32.641184500   File "/data/etc/dbus-mqtt-grid/dbus-mqtt-grid.py", line 262, in _update
2023-05-22 18:12:32.641187500     self._dbusservice['/Ac/L1/Frequency'] = round(grid_L1_frequency, 2)
```

Obviously, this is because grid_L1_frequency is None unless transmitted. Commenting out the 3 lines for frequency of L1/L2/l3 works for me, but this is ugly.
Sorry for knowing to little about Python and internals to submit a fix - great work!

**Comment by mr-manuel** [comment]
Hi @gvzdus,

thanks for reporting and helping improving the driver. A new version with a fix was released just now.

https://github.com/mr-manuel/venus-os_dbus-mqtt-grid/releases/tag/v0.1.3

Please give me a short feedback, if the issue is solved.

**Comment by gvzdus** [comment]
For better readability:
...
023-05-22 19:27:57.445533500 Traceback (most recent call last):
2023-05-22 19:27:57.445541500   File "/data/etc/dbus-mqtt-grid/dbus-mqtt-grid.py", line 285, in _update
2023-05-22 19:27:57.445545500     self._dbusservice['/Ac/L3/Frequency'] = round(grid_L3_frequency, 2) if grid_L3_frequency is not None else None
2023-05-22 19:27:57.445549500   File "/data/etc/dbus-mqtt-grid/ext/velib_python/vedbus.py", line 157, in __setitem__
2023-05-22 19:27:57.445553500     self._dbusobjects[path].local_set_value(newvalue)
2023-05-22 19:27:57.445556500 KeyError: '/Ac/L3/Frequency'
...

**Comment by mr-manuel** [comment]
Can you post the JSON you are sending?

**Comment by gvzdus** [comment]
mosquitto_sub -v -h 192.168.0.46 -t '#' 
```
N/c0619ab37eef/keepalive {"value": 1}
N/c0619ab37eef/system/0/Serial {"value": "c0619ab37eef"}
fhem/meter {"grid":{"power":-28,"L1":{"power":14},"L2":{"power":-126},"L3":{"power":86}}}
fhem/meter {"grid":{"power":8,"L1":{"power":15},"L2":{"power":-93},"L3":{"power":85}}}

```

**Comment by mr-manuel** [comment]
Found the typo. Can you download the script from the repo and try again?
